/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdsRouteImport } from './routes/ads'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as CmRouteImport } from './routes/cm'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as CmIndexRouteImport } from './routes/cm.index'
import { Route as CmCalendarRouteImport } from './routes/cm.calendar'
import { Route as CmConfigRouteImport } from './routes/cm.config'
import { Route as CmPostsRouteImport } from './routes/cm.posts'
import { Route as CmStudioImageRouteImport } from './routes/cm.studio-image'
import { Route as CmStudioVideoRouteImport } from './routes/cm.studio-video'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdsRoute = AdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const CmRoute = CmRouteImport.update({
  id: '/cm',
  path: '/cm',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const CmIndexRoute = CmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CmRoute,
} as any)
const CmCalendarRoute = CmCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => CmRoute,
} as any)
const CmConfigRoute = CmConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => CmRoute,
} as any)
const CmPostsRoute = CmPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => CmRoute,
} as any)
const CmStudioImageRoute = CmStudioImageRouteImport.update({
  id: '/studio-image',
  path: '/studio-image',
  getParentRoute: () => CmRoute,
} as any)
const CmStudioVideoRoute = CmStudioVideoRouteImport.update({
  id: '/studio-video',
  path: '/studio-video',
  getParentRoute: () => CmRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ads': typeof AdsRoute
  '/campaigns': typeof CampaignsRoute
  '/cm': typeof CmRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/stats': typeof StatsRoute
  '/cm/calendar': typeof CmCalendarRoute
  '/cm/config': typeof CmConfigRoute
  '/cm/posts': typeof CmPostsRoute
  '/cm/studio-image': typeof CmStudioImageRoute
  '/cm/studio-video': typeof CmStudioVideoRoute
  '/cm/': typeof CmIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ads': typeof AdsRoute
  '/campaigns': typeof CampaignsRoute
  '/dashboard': typeof DashboardRoute
  '/stats': typeof StatsRoute
  '/cm/calendar': typeof CmCalendarRoute
  '/cm/config': typeof CmConfigRoute
  '/cm/posts': typeof CmPostsRoute
  '/cm/studio-image': typeof CmStudioImageRoute
  '/cm/studio-video': typeof CmStudioVideoRoute
  '/cm': typeof CmIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ads': typeof AdsRoute
  '/campaigns': typeof CampaignsRoute
  '/cm': typeof CmRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/stats': typeof StatsRoute
  '/cm/calendar': typeof CmCalendarRoute
  '/cm/config': typeof CmConfigRoute
  '/cm/posts': typeof CmPostsRoute
  '/cm/studio-image': typeof CmStudioImageRoute
  '/cm/studio-video': typeof CmStudioVideoRoute
  '/cm/': typeof CmIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ads'
    | '/campaigns'
    | '/cm'
    | '/dashboard'
    | '/stats'
    | '/cm/calendar'
    | '/cm/config'
    | '/cm/posts'
    | '/cm/studio-image'
    | '/cm/studio-video'
    | '/cm/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ads'
    | '/campaigns'
    | '/dashboard'
    | '/stats'
    | '/cm/calendar'
    | '/cm/config'
    | '/cm/posts'
    | '/cm/studio-image'
    | '/cm/studio-video'
    | '/cm'
  id:
    | '__root__'
    | '/'
    | '/ads'
    | '/campaigns'
    | '/cm'
    | '/dashboard'
    | '/stats'
    | '/cm/calendar'
    | '/cm/config'
    | '/cm/posts'
    | '/cm/studio-image'
    | '/cm/studio-video'
    | '/cm/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdsRoute: typeof AdsRoute
  CampaignsRoute: typeof CampaignsRoute
  CmRoute: typeof CmRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  StatsRoute: typeof StatsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ads': {
      id: '/ads'
      path: '/ads'
      fullPath: '/ads'
      preLoaderRoute: typeof AdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cm': {
      id: '/cm'
      path: '/cm'
      fullPath: '/cm'
      preLoaderRoute: typeof CmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cm/': {
      id: '/cm/'
      path: '/'
      fullPath: '/cm/'
      preLoaderRoute: typeof CmIndexRouteImport
      parentRoute: typeof CmRoute
    }
    '/cm/calendar': {
      id: '/cm/calendar'
      path: '/calendar'
      fullPath: '/cm/calendar'
      preLoaderRoute: typeof CmCalendarRouteImport
      parentRoute: typeof CmRoute
    }
    '/cm/config': {
      id: '/cm/config'
      path: '/config'
      fullPath: '/cm/config'
      preLoaderRoute: typeof CmConfigRouteImport
      parentRoute: typeof CmRoute
    }
    '/cm/posts': {
      id: '/cm/posts'
      path: '/posts'
      fullPath: '/cm/posts'
      preLoaderRoute: typeof CmPostsRouteImport
      parentRoute: typeof CmRoute
    }
    '/cm/studio-image': {
      id: '/cm/studio-image'
      path: '/studio-image'
      fullPath: '/cm/studio-image'
      preLoaderRoute: typeof CmStudioImageRouteImport
      parentRoute: typeof CmRoute
    }
    '/cm/studio-video': {
      id: '/cm/studio-video'
      path: '/studio-video'
      fullPath: '/cm/studio-video'
      preLoaderRoute: typeof CmStudioVideoRouteImport
      parentRoute: typeof CmRoute
    }
  }
}

interface CmRouteChildren {
  CmCalendarRoute: typeof CmCalendarRoute
  CmConfigRoute: typeof CmConfigRoute
  CmPostsRoute: typeof CmPostsRoute
  CmStudioImageRoute: typeof CmStudioImageRoute
  CmStudioVideoRoute: typeof CmStudioVideoRoute
  CmIndexRoute: typeof CmIndexRoute
}

const CmRouteChildren: CmRouteChildren = {
  CmCalendarRoute: CmCalendarRoute,
  CmConfigRoute: CmConfigRoute,
  CmPostsRoute: CmPostsRoute,
  CmStudioImageRoute: CmStudioImageRoute,
  CmStudioVideoRoute: CmStudioVideoRoute,
  CmIndexRoute: CmIndexRoute,
}

const CmRouteWithChildren = CmRoute._addFileChildren(CmRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdsRoute: AdsRoute,
  CampaignsRoute: CampaignsRoute,
  CmRoute: CmRouteWithChildren,
  DashboardRoute: DashboardRoute,
  StatsRoute: StatsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
